/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosTelas;

import Classes.DadosFacade;
import Classes.Evento;
import Classes.User;
import java.util.ArrayList;

/**
 *
 * @author zebodexx
 */
public class formMenuPrincipal extends javax.swing.JFrame {

    private DadosFacade dadosList;
    private String userLogado;

    public void carregarDados(DadosFacade dadosCarregados) {
        this.dadosList = dadosCarregados;
    }

    public void getUser(String userLogado) {
        this.userLogado = userLogado;
    }

    public formMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonCadastrarEvento = new javax.swing.JButton();
        buttonMostrarEventos = new javax.swing.JButton();
        buttonComparIngressos = new javax.swing.JButton();
        buttonSairMenu = new javax.swing.JButton();
        buttonMeusIngressos = new javax.swing.JButton();
        buttonsAlterarSenha = new javax.swing.JButton();
        buttonAlterDadosEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILHETERIA DIGITAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("MENU PRINCIPAL");

        jLabel3.setText("Escolha alguma das seguintes opcoes para prosseguir:");

        buttonCadastrarEvento.setText("CADASTRAR NOVO EVENTO");
        buttonCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarEventoActionPerformed(evt);
            }
        });

        buttonMostrarEventos.setText("MOSTRAR EVENTOS");
        buttonMostrarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarEventosActionPerformed(evt);
            }
        });

        buttonComparIngressos.setText("COMPRA INGRESSOS");
        buttonComparIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComparIngressosActionPerformed(evt);
            }
        });

        buttonSairMenu.setText("SAIR");
        buttonSairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairMenuActionPerformed(evt);
            }
        });

        buttonMeusIngressos.setText("MEUS INGRESSOS");
        buttonMeusIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMeusIngressosActionPerformed(evt);
            }
        });

        buttonsAlterarSenha.setText("ALTERA SENHA");
        buttonsAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsAlterarSenhaActionPerformed(evt);
            }
        });

        buttonAlterDadosEvento.setText("ALTERAR DADOS EVENTO");
        buttonAlterDadosEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterDadosEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonComparIngressos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonMostrarEventos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCadastrarEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonMeusIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonsAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAlterDadosEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(buttonSairMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrarEvento)
                    .addComponent(buttonMeusIngressos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMostrarEventos)
                    .addComponent(buttonsAlterarSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonComparIngressos)
                    .addComponent(buttonAlterDadosEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSairMenu)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairMenuActionPerformed
        formLogin telaLogin = new formLogin();
        telaLogin.carregarDados(dadosList);
        this.setVisible(false);
        telaLogin.setVisible(true);
    }//GEN-LAST:event_buttonSairMenuActionPerformed

    private void buttonCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarEventoActionPerformed
        formCadastrarEvento telaCadEvento = new formCadastrarEvento();
        telaCadEvento.carregarDados(dadosList);
        telaCadEvento.getUser(userLogado);
        this.setVisible(false);
        telaCadEvento.setVisible(true);
    }//GEN-LAST:event_buttonCadastrarEventoActionPerformed

    private void buttonMostrarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarEventosActionPerformed
        formMostrarIngressos telaMostrarEventos = new formMostrarIngressos(dadosList.getEventos());
        telaMostrarEventos.carregarDados(dadosList);
        telaMostrarEventos.getUser(userLogado);
        this.setVisible(false);
        telaMostrarEventos.setVisible(true);
    }//GEN-LAST:event_buttonMostrarEventosActionPerformed

    private void buttonsAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsAlterarSenhaActionPerformed
        formAlterarSenha telaAlterarSenha = new formAlterarSenha();
        telaAlterarSenha.carregarDados(dadosList);
        telaAlterarSenha.getUser(userLogado);
        this.setVisible(false);
        telaAlterarSenha.setVisible(true);
    }//GEN-LAST:event_buttonsAlterarSenhaActionPerformed

    private void buttonComparIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComparIngressosActionPerformed
        formComprarIngressos telaComprarIngressos = new formComprarIngressos(dadosList.getEventos());
        telaComprarIngressos.carregarDados(dadosList);
        telaComprarIngressos.getUser(userLogado);
        this.setVisible(false);
        telaComprarIngressos.setVisible(true);
    }//GEN-LAST:event_buttonComparIngressosActionPerformed

    private void buttonMeusIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMeusIngressosActionPerformed
        int indiceUser = dadosList.indexUser(userLogado);
        ArrayList<User> usuarios = dadosList.getUsers();
        ArrayList<Evento> meusIngressos = usuarios.get(indiceUser).getMeusEventos();
        formMostrarMeusIngressos telaMeusIngressos = new formMostrarMeusIngressos(meusIngressos);
        telaMeusIngressos.carregarDados(dadosList);
        telaMeusIngressos.getUser(userLogado);
        this.setVisible(false);
        telaMeusIngressos.setVisible(true);
    }//GEN-LAST:event_buttonMeusIngressosActionPerformed

    private void buttonAlterDadosEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterDadosEventoActionPerformed
        formAlterarDadosEvento telaAlterarDados = new formAlterarDadosEvento();
        telaAlterarDados.carregarDados(dadosList);
        telaAlterarDados.getUser(userLogado);
        this.setVisible(false);
        telaAlterarDados.setVisible(true);
    }//GEN-LAST:event_buttonAlterDadosEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterDadosEvento;
    private javax.swing.JButton buttonCadastrarEvento;
    private javax.swing.JButton buttonComparIngressos;
    private javax.swing.JButton buttonMeusIngressos;
    private javax.swing.JButton buttonMostrarEventos;
    private javax.swing.JButton buttonSairMenu;
    private javax.swing.JButton buttonsAlterarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
